__author__ = 'gkannappan'

from textblob import TextBlob
import pandas
from django.utils.encoding import smart_str, smart_unicode



#sample = "i couldn't recommend a product less.            if you're filing from overseas in particular i'd really advise you to stay away from this. there are numerous issues filing from overseas that will cause problems. one immediate problem is the difficulty in getting someone on the line. their phone menu system is not too friendly for overseas numbers.            another issue was the lack of transparency in the pricing. it was only at the end of the process that they tell you you have to pay an extra fee for them processing a credit card payment. mine rang up at almost $90 more just for processing it - that's in addition to the cost of the software package. what's worse is after multiple attempts of nearly completing the process i was informed that the state where i needed to file didn't accept overseas payments/addresses. in short, i've wasted a lot time and i'm now late filing.            turbo tax could be a whole lot more transparent about the packages and how they're going to add on to your bill.|hidden charges and filing problems"
#Sentiment(polarity=0.0609375, subjectivity=0.375)
#sample = "best tax preparation software.  saved me a bundle.|best tax preparation software.  saved me a bundle."
ReviewText = pandas.read_csv("/Users/gkannappan/Documents/Intuit/Analytics Playground/Text Classification/AUTUMN/AMZN_Disc_DF2.txt", delimiter= '|', index_col=False, header=0, usecols=[0,1,2,3,4]);
rev_text = ReviewText['ReviewText'].tolist()
rev_title = ReviewText['ReviewTitle'].tolist()

'''
sample = ["i couldn't recommend a product less.            if you're filing from overseas in particular i'd really advise you to stay away from this. there are numerous issues filing from overseas that will cause problems. one immediate problem is the difficulty in getting someone on the line. their phone menu system is not too friendly for overseas numbers.            another issue was the lack of transparency in the pricing. it was only at the end of the process that they tell you you have to pay an extra fee for them processing a credit card payment. mine rang up at almost $90 more just for processing it - that's in addition to the cost of the software package. what's worse is after multiple attempts of nearly completing the process i was informed that the state where i needed to file didn't accept overseas payments/addresses. in short, i've wasted a lot time and i'm now late filing.            turbo tax could be a whole lot more transparent about the packages and how they're going to add on to your bill.|hidden charges and filing problems",
          "i purchased this product on january 26, 2016.to use in figuring and submitting my federal and state taxes for 2015 . upon receipt, i put it away since there was no need to use it immediately. i retrieved it last week to submit my taxes before the deadline. no matter what i did, the program would not load on my computer even though i had no trouble loading the same product in previous years on the same computer. i contacted amazon only to find out that the return date had expired and was not eligible for return. i do not feel i should be penalized for a defective product even if the return date has expired since this is a one time use product tied to a specific date.",
          "best tax preparation software.  saved me a bundle.",
          "easy to do your taxes but they nickel and dime you when it comes to filing your state return. $25 to process a state return? will be looking for other options next year.",
          "don't care for the hidden fees will not use next year!!!",
          "deceptive that the electronic filing of the first state was not included in the price.  wanted another $45 for the second state, but at least filled them out correctly.  they wanted another $90 to file the two states electronically.  so i would have rated them excellent if they weren't greedy and deceptive!",
          "purposeful lack of information/disinformation and intrusive upselling/cross-selling make this a poor investment",
          "turbotax made it very clear to me that the software purchased from amazon was quirky and had issues. they reloaded the same version for me.            do they just want to sell it direct or was it really defective? they also don't tell you it doesn't include state filing on line or more than one state. you have to pay turbotax extra- twice what you paid for the software!            amazon should make that clear to buyers- if they ever knew. i am not blaming amazon.  turbotax shouldn't sell a product that is defective and should have better transparency about the real filing costs.",
          "i have used turbotax for years but will not be using them again. when i went to do my taxes this year and after doing all of my federal return, the state would not load. i contacted turbotax customer service, and they couldn't get the state to load either. so they said i had to start all over, do my taxes online, enter everything manually and would have to pay an additional $95. unfortunately, i purchased my turbotax from amazon early, and by the time i did my taxes, it was beyond the return time so i was completely out of the money i spent on this package. i bought h&r block instead. federal and state downloaded onto my computer correctly in a matter of minutes.  it interfaced with my previous return and uploaded most of my information for my returns. they were done very quickly, and it only cost $55 , not the $95 that turbotax wanted to charge me to do my taxes online.",
          "software is incomplete and buggy, but that's the customers problem, not intuit, or at least that what they told me. ""we can't figure out why it doesn't work, but you've already paid so it's not our problem."" this after a full day on hold with ""experts"".",
          "i wish to have my money back. it would not work for me & three calls to intuit & still no help. they promised to call back & never did!!!            rev richard n davis sr|bad, bad buy!",
          "i would return it if i could.|one star",
          "the worst turbo tax ever, did not print all forms and missed some forms from the transfer but managed to get what i needed from the program.  not amazons fault  its intuit not testing there product before putting it out there.|terrible tax",
          "i would normally give them a 4-5 star rating. first of all state filings are supposed to be $19.99. when submitting they jacked up both states to $24.99 even though the program stated $19.99 at the start of efiling. also since i filed after 4/18 which is not a problem if you don't owe anyone any money (fyi penalties and interest are based on owed money so if you don't owe money then there is no reason to file an extension), there was an update with a serious flaw in the program. anyone who filed before 4/20 probably wouldn't check there taxes. apparently one of the forms in the program was putting some sort of college scholarships or something into a return as taxable income when it shouldn't be. if you have college financial info in your return you better check the possible impact on this.|charge $5 more than advertised for efile of state returns, update on 4/20 has major impact on possible college scholarship info",
          "waste of money.  it wouldn't upload to my computer so i had to repurchase it online.|ripoff",
          "i couldn't recommend a product less.            if you're filing from overseas in particular i'd really advise you to stay away from this. there are numerous issues filing from overseas that will cause problems. one immediate problem is the difficulty in getting someone on the line. their phone menu system is not too friendly for overseas numbers.            another issue was the lack of transparency in the pricing. it was only at the end of the process that they tell you you have to pay an extra fee for them processing a credit card payment. mine rang up at almost $90 more just for processing it - that's in addition to the cost of the software package. what's worse is after multiple attempts of nearly completing the process i was informed that the state where i needed to file didn't accept overseas payments/addresses. in short, i've wasted a lot time and i'm now late filing.            turbo tax could be a whole lot more transparent about the packages and how they're going to add on to your bill.|hidden charges and filing problems"
          "intuit gave me the $4,000 credit for making less than the amount listed on 1040, then it subtracted it, showing me owing over $4,000 in taxes.  i have taken this credit every year since it was implemented and never had it questioned.  so i deleted the completed 1040, started over and this time intuit showed i would get a $58 refund.  i did my taxes manually and will be receiving a $348 refund!  i think i should be getting a refund from intuit,|intuit gave me the $4, 000 credit for making ...",
          "this software is junk.  i had used it on prior years except 2014, now i know why.  too many bugs, this time it won't install.  support is non existent, 2 hours on hold.  not wasting my time anymore with this software.  h&r i'm yours from now on.  intuit, you have stolen your last $45 from me!|sucks!",
          "my fault, i guess.  i bought this disc, trusting that it would install correctly and prepare my forms on the due date. when i only got repeated error messages on the install, i had to go to their website and prepare online - and pay for the software again, by the way. i've been preparing my federal return with turbotax since it was macintax. will never do it again - hr block, here i come.|just go somewhere else",
          "it is the same product i've been using, more or less, for the last decade. it is good solid software for preparing returns. but i've got to agree with the others here. the hidden ""fees"" that keep popping up through the process need to be laid out for the consumer prior to purchase. this particular package is a ""+ state taxes"" but doesn't include the $24.99 (minnesota) filing fee. nor does it include the $34.99 fee that you must pay in order to deduct your filing fee directly from your refund. i could go on. the bottom line is that we, the consumers, don't need everything to be 'free' - we just need to know what we're signing up to pay for before we're fully committed. this year's turbotax falls well short of that clear expectation.",
          "what they don't tell you is that after you complete your state tax filing, and choose to submit it electronically, they ask for your credit card so they can charge you another $24.99 for filing electronically. pretty sleazy approach. won't be using them next year.|hidden add on fee",
          "this software assumes that you are connected to the internet 24/7.  i'm not so i buy the cd version and go to a public network to install the updates.  it awkwardly installs and updates the federal software after i skip the different windows wanting me to enter personal information.  i have been unable to figure out whether i have the state software installed or not - it won't ask me to select which state and install so i assume that i don't.  it keeps trying to sell me state software that i've already paid for when i purchased the cd (federal + state + federal e-file).  i don't want to e-file my state, i just want to use the software i paid for to fill out the necessary forms.  the assumption that everyone is comfortable filling out forms with personal financial information while on-line is flawed.  there should be an easy installation process where you pop the cd in, indicate which state you want, the cd installs the base software for both federal and the selected state, and then goes out to the network to install all updates for federal and state.  this should be doable before you have to create a return.  this is painful.|turbotax not friendly for off-line use",
          "deceptive"
          ]
'''

rev = ["{} {}".format(a_, b_.strip()) for a_, b_ in zip(rev_text, rev_title)]


for i in rev:
    #print i
    #print smart_str(i)
    #print TextBlob(str(i.encode('utf-8'))).sentiment.polarity
    try :
        print TextBlob(smart_str(i.encode('utf-8'))).sentiment.polarity
    except UnicodeDecodeError:
        print 'NA'


#sample_text = TextBlob(sample)

#print sample_text.sentiment
